### 문제상황 - Error메시지 검증하는방법
Jest에서는 안타깝게도 현재의 Jest 버전에서 toThrowErrorMatchingObject 매처는 Error 객체의 message 프로퍼티와 일치하는지를 검증하지만, <br>
특정 예외 클래스에 대한 추가 속성을 검증하지는 않습니다. <br>
그래서 같은예외라도 분명 메시지가 다를텐데 같다고하니까 방법이 있는지 궁금했다 <br>



### 해결방법
new를 통해서 메시지를 넣어서 검증해버리면 된다. 천재다
```ts
  test('createCategory Fail', async () => {
    const categoryName = '상의';
    const dto = {
      name: categoryName,
    };
    categoryRepository.exists.mockResolvedValue(true);
    await expect(categoryService.createCategory(dto)).rejects.toThrow(
      new BadRequestException('hello'),
    );
    expect(categoryRepository.exists).toHaveBeenCalled();
  });

    await expect(categoryService.createCategory(dto)).rejects.toThrow(
      BadRequestException,
    );
    expect(categoryRepository.exists).toHaveBeenCalled();
  });
```
<https://jojoldu.tistory.com/656>
